// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"user/models"
)

// UserCreateCreatedCode is the HTTP code returned for type UserCreateCreated
const UserCreateCreatedCode int = 201

/*
UserCreateCreated Created

swagger:response userCreateCreated
*/
type UserCreateCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewUserCreateCreated creates UserCreateCreated with default headers values
func NewUserCreateCreated() *UserCreateCreated {

	return &UserCreateCreated{}
}

// WithPayload adds the payload to the user create created response
func (o *UserCreateCreated) WithPayload(payload *models.User) *UserCreateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user create created response
func (o *UserCreateCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserCreateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
UserCreateDefault Error handling the request

swagger:response userCreateDefault
*/
type UserCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUserCreateDefault creates UserCreateDefault with default headers values
func NewUserCreateDefault(code int) *UserCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &UserCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the user create default response
func (o *UserCreateDefault) WithStatusCode(code int) *UserCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the user create default response
func (o *UserCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the user create default response
func (o *UserCreateDefault) WithPayload(payload *models.Error) *UserCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the user create default response
func (o *UserCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UserCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
