// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/swag"
)

// UserListURL generates an URL for the user list operation
type UserListURL struct {
	Country   *string
	Email     *string
	FirstName *string
	LastName  *string
	Nickname  *string
	Page      *int64
	PerPage   *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UserListURL) WithBasePath(bp string) *UserListURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UserListURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *UserListURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/v1/user"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var countryQ string
	if o.Country != nil {
		countryQ = *o.Country
	}
	if countryQ != "" {
		qs.Set("country", countryQ)
	}

	var emailQ string
	if o.Email != nil {
		emailQ = *o.Email
	}
	if emailQ != "" {
		qs.Set("email", emailQ)
	}

	var firstNameQ string
	if o.FirstName != nil {
		firstNameQ = *o.FirstName
	}
	if firstNameQ != "" {
		qs.Set("first_name", firstNameQ)
	}

	var lastNameQ string
	if o.LastName != nil {
		lastNameQ = *o.LastName
	}
	if lastNameQ != "" {
		qs.Set("last_name", lastNameQ)
	}

	var nicknameQ string
	if o.Nickname != nil {
		nicknameQ = *o.Nickname
	}
	if nicknameQ != "" {
		qs.Set("nickname", nicknameQ)
	}

	var pageQ string
	if o.Page != nil {
		pageQ = swag.FormatInt64(*o.Page)
	}
	if pageQ != "" {
		qs.Set("page", pageQ)
	}

	var perPageQ string
	if o.PerPage != nil {
		perPageQ = swag.FormatInt64(*o.PerPage)
	}
	if perPageQ != "" {
		qs.Set("per_page", perPageQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *UserListURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *UserListURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *UserListURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on UserListURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on UserListURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *UserListURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
