// Code generated by go-swagger; DO NOT EDIT.

package monitoring

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"user/models"
)

// GetMonPingOKCode is the HTTP code returned for type GetMonPingOK
const GetMonPingOKCode int = 200

/*
GetMonPingOK Health OK

swagger:response getMonPingOK
*/
type GetMonPingOK struct {

	/*
	  In: Body
	*/
	Payload *GetMonPingOKBody `json:"body,omitempty"`
}

// NewGetMonPingOK creates GetMonPingOK with default headers values
func NewGetMonPingOK() *GetMonPingOK {

	return &GetMonPingOK{}
}

// WithPayload adds the payload to the get mon ping o k response
func (o *GetMonPingOK) WithPayload(payload *GetMonPingOKBody) *GetMonPingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get mon ping o k response
func (o *GetMonPingOK) SetPayload(payload *GetMonPingOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMonPingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetMonPingDefault Error handling the request

swagger:response getMonPingDefault
*/
type GetMonPingDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMonPingDefault creates GetMonPingDefault with default headers values
func NewGetMonPingDefault(code int) *GetMonPingDefault {
	if code <= 0 {
		code = 500
	}

	return &GetMonPingDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get mon ping default response
func (o *GetMonPingDefault) WithStatusCode(code int) *GetMonPingDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get mon ping default response
func (o *GetMonPingDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get mon ping default response
func (o *GetMonPingDefault) WithPayload(payload *models.Error) *GetMonPingDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get mon ping default response
func (o *GetMonPingDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMonPingDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
